version: '3'
services:
  backend:
    build: ./app
    ports:
      - 5000:5000
    env_file:
      - .env
    develop:
      watch:
        - action: sync
          path: ./app/src
          target: /app
        - action: sync+restart
          path: ./app/src/entrypoint.py
          target: /app/src/entrypoint.py
        - action: rebuild
          path: ./app/requirements.txt
